apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yvqg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-yvqg@sha256:106fb2cb2e441f402272fbae41c8e46e9792f15eaa6a3af1b31da0db050abb8e
        name: my-nodejs
        resources: {}
status: {}
